//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Viiar.AtmFinder.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Viiar.AtmFinder.UI.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been in situation when you need to get some cash to make important payment or order some service, but you have no idea where could be nearest ATM machine? With ATM finder you can easily find cash nearby. Application also shows bank offices and cash-in machines. The list can be configured. You can set your home bank and set to show only those..
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With the ATM Finder app you will be able to find your cash nearby easily..
        /// </summary>
        public static string AboutIntro {
            get {
                return ResourceManager.GetString("AboutIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string AboutPivotHeading {
            get {
                return ResourceManager.GetString("AboutPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to appearance.
        /// </summary>
        public static string AppearancePivotHeading {
            get {
                return ResourceManager.GetString("AppearancePivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM Finder.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change view.
        /// </summary>
        public static string ArealViewBarButton {
            get {
                return ResourceManager.GetString("ArealViewBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author: Valdis Iljuconoks, MVP C#
        ///http://www.dotnet.lv/blogs/vi/
        ///Copyright © Valdis Iljuconoks, 2012.
        /// </summary>
        public static string Authors {
            get {
                return ResourceManager.GetString("Authors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash in.
        /// </summary>
        public static string CashInIconText {
            get {
                return ResourceManager.GetString("CashInIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash in.
        /// </summary>
        public static string CashInPivotHeading {
            get {
                return ResourceManager.GetString("CashInPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash out.
        /// </summary>
        public static string CashOutIconText {
            get {
                return ResourceManager.GetString("CashOutIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cash out.
        /// </summary>
        public static string CashOutPivotHeading {
            get {
                return ResourceManager.GetString("CashOutPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my position.
        /// </summary>
        public static string CenterMeBarButton {
            get {
                return ResourceManager.GetString("CenterMeBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commission withdrawal.
        /// </summary>
        public static string CommissionWithDrawalLongSign {
            get {
                return ResourceManager.GetString("CommissionWithDrawalLongSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to commission.
        /// </summary>
        public static string CommissionWithDrawalSign {
            get {
                return ResourceManager.GetString("CommissionWithDrawalSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to connectivity.
        /// </summary>
        public static string ConnectivityPivotHeading {
            get {
                return ResourceManager.GetString("ConnectivityPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact by email: valdis.iljuconoks@dotnet.lv.
        /// </summary>
        public static string ContactByEmail {
            get {
                return ResourceManager.GetString("ContactByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountrySettingText {
            get {
                return ResourceManager.GetString("CountrySettingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count to show.
        /// </summary>
        public static string CountToShowSettingsText {
            get {
                return ResourceManager.GetString("CountToShowSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to details.
        /// </summary>
        public static string DetailsPageTitle {
            get {
                return ResourceManager.GetString("DetailsPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directions.
        /// </summary>
        public static string DirectionsBarButton {
            get {
                return ResourceManager.GetString("DirectionsBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to valdis.iljuconoks@dotnet.lv.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seems like closest ATM is pretty far away..
        /// </summary>
        public static string EntityTooFarMessage {
            get {
                return ResourceManager.GetString("EntityTooFarMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services are not enabled.
        ///Navigate to Settings page in order to enable location services usage in the application..
        /// </summary>
        public static string LocationServicesNotEnabledError {
            get {
                return ResourceManager.GetString("LocationServicesNotEnabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services.
        /// </summary>
        public static string LocationServicesSettingsText {
            get {
                return ResourceManager.GetString("LocationServicesSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to map.
        /// </summary>
        public static string MapBarButton {
            get {
                return ResourceManager.GetString("MapBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to my bank.
        /// </summary>
        public static string MyBankPivotHeading {
            get {
                return ResourceManager.GetString("MyBankPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My bank.
        /// </summary>
        public static string MyBankSettingsText {
            get {
                return ResourceManager.GetString("MyBankSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *** Running in language which is not natively supported in OS.
        ///
        ///Have you ever been in situation when you need to get some cash to make important payment or order some service, but you have no idea where could be nearest ATM machine? With ATM finder you can easily find cash nearby. Application also shows bank offices and cash-in machines. The list can be configured. You can set your home bank and set to show only those..
        /// </summary>
        public static string NativeOSLanguageWarning {
            get {
                return ResourceManager.GetString("NativeOSLanguageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nearby.
        /// </summary>
        public static string NearbyPivotHeading {
            get {
                return ResourceManager.GetString("NearbyPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to office.
        /// </summary>
        public static string OfficeIconText {
            get {
                return ResourceManager.GetString("OfficeIconText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offices.
        /// </summary>
        public static string OfficesPivotHeading {
            get {
                return ResourceManager.GetString("OfficesPivotHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online services (Windows © Azure).
        /// </summary>
        public static string OnlineServicesSettingsText {
            get {
                return ResourceManager.GetString("OnlineServicesSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy:
        ///ATM Finder respects user privacy and therefore no user information is collected nor stored.
        ///ATM Finder uses location services to detect device location to provide information about closest ATM machine or bank office.
        ///Data collected from location service are not stored or forwarded.
        ///User always is able to switch off location service usage in ATM Finder..
        /// </summary>
        public static string Privacy {
            get {
                return ResourceManager.GetString("Privacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate app on marketplace.
        /// </summary>
        public static string RateApplication {
            get {
                return ResourceManager.GetString("RateApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to refresh.
        /// </summary>
        public static string RefreshBarButton {
            get {
                return ResourceManager.GetString("RefreshBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to report.
        /// </summary>
        public static string ReportBarButton {
            get {
                return ResourceManager.GetString("ReportBarButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsMenuItem {
            get {
                return ResourceManager.GetString("SettingsMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to general.
        /// </summary>
        public static string SettingsPageName {
            get {
                return ResourceManager.GetString("SettingsPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show coordinates.
        /// </summary>
        public static string ShowCoordinatesSettingsText {
            get {
                return ResourceManager.GetString("ShowCoordinatesSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show map on startup.
        /// </summary>
        public static string ShowMapOnStartupSettingsText {
            get {
                return ResourceManager.GetString("ShowMapOnStartupSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show only my bank.
        /// </summary>
        public static string ShowOnlyMyBankSettingsText {
            get {
                return ResourceManager.GetString("ShowOnlyMyBankSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM (cash in).
        /// </summary>
        public static string ShowTypesOfCashInSettingsText {
            get {
                return ResourceManager.GetString("ShowTypesOfCashInSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ATM (cash out).
        /// </summary>
        public static string ShowTypesOfCashOutSettingsText {
            get {
                return ResourceManager.GetString("ShowTypesOfCashOutSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offices.
        /// </summary>
        public static string ShowTypesOfOfficesSettingsText {
            get {
                return ResourceManager.GetString("ShowTypesOfOfficesSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show types of.
        /// </summary>
        public static string ShowTypesOfSettingsText {
            get {
                return ResourceManager.GetString("ShowTypesOfSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shops.
        /// </summary>
        public static string ShowTypesOfShopsSettingsText {
            get {
                return ResourceManager.GetString("ShowTypesOfShopsSettingsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to somewhere here.
        /// </summary>
        public static string SomewhereHere {
            get {
                return ResourceManager.GetString("SomewhereHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your current location.
        /// </summary>
        public static string StartLocationMapDirections {
            get {
                return ResourceManager.GetString("StartLocationMapDirections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string SwitchedOff {
            get {
                return ResourceManager.GetString("SwitchedOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string SwitchedOn {
            get {
                return ResourceManager.GetString("SwitchedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Versions:
        ///
        ///v 2.0
        ///- Added Windows Azure backend
        ///- Fixed some bugs
        ///- Added some banks in all Baltic states
        ///
        ///v 1.2
        ///- Fixed some bugs
        ///
        ///v 1.1
        ///- Added multi-country feature
        ///- Added Swebdank and Nordea banks (Estonia)
        ///- Added Swebdank and Nordea banks (Lithiania)
        ///- Added SEB bank (Eastonia and Lithiania)
        ///- Added DNB bank (Lithiania)
        ///- Fixed some friendly chain info issues
        ///
        ///v 1.0
        ///- Added Swedbank, Nordea, Citadele and DNB banks (Latvia territory)
        ///- Added Hipoteku and SEB banks (Latvia territory) [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Versions {
            get {
                return ResourceManager.GetString("Versions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom to closest.
        /// </summary>
        public static string ZoomToClosestSettingsText {
            get {
                return ResourceManager.GetString("ZoomToClosestSettingsText", resourceCulture);
            }
        }
    }
}
