//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.ListSampleDataSource
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class ListSampleDataSource { }
#else

	public class ListSampleDataSource : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public ListSampleDataSource()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/Viiar.AtmFinder.UI;component/SampleData/ListSampleDataSource/ListSampleDataSource.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private ItemCollection _Collection = new ItemCollection();

		public ItemCollection Collection
		{
			get
			{
				return this._Collection;
			}
		}
	}

	public class ItemCollection : System.Collections.ObjectModel.ObservableCollection<Item>
	{ 
	}

	public class Item : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _TitleShort = string.Empty;

		public string TitleShort
		{
			get
			{
				return this._TitleShort;
			}

			set
			{
				if (this._TitleShort != value)
				{
					this._TitleShort = value;
					this.OnPropertyChanged("TitleShort");
				}
			}
		}

		private System.Windows.Media.ImageSource _SmallIcon = null;

		public System.Windows.Media.ImageSource SmallIcon
		{
			get
			{
				return this._SmallIcon;
			}

			set
			{
				if (this._SmallIcon != value)
				{
					this._SmallIcon = value;
					this.OnPropertyChanged("SmallIcon");
				}
			}
		}

		private string _AddressShort = string.Empty;

		public string AddressShort
		{
			get
			{
				return this._AddressShort;
			}

			set
			{
				if (this._AddressShort != value)
				{
					this._AddressShort = value;
					this.OnPropertyChanged("AddressShort");
				}
			}
		}

		private string _DistanceView = string.Empty;

		public string DistanceView
		{
			get
			{
				return this._DistanceView;
			}

			set
			{
				if (this._DistanceView != value)
				{
					this._DistanceView = value;
					this.OnPropertyChanged("DistanceView");
				}
			}
		}
	}
#endif
}
